# Creating Quarto Book
# https://quarto.org/docs/books/
#
# options for Quarto book
# https://quarto.org/docs/reference/projects/books.html
#
# Options for html
# https://quarto.org/docs/reference/projects/websites.html#section

project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - eda/*.qmd
    - appx/*.qmd
    - wa/*.qmd
  # resources:  # in case something was not included in rendered site automatically
  #   - "data/*"
  #   - "images/*"



number-depth: 2



website:
  title: "WNBA Draft Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: EDA
        menu:
          - href: eda/eda-member1.qmd
            text: Will
          - href: eda/eda-member2.qmd
            text: Hamza
          - href: eda/eda-member3.qmd
            text: Nox
      - text: Appendices
        menu:
          - href: appx/proposal.qmd
            text: Proposal
          - href: appx/case-study.qmd
            text: Case Study
          - href: wa/wa-member1.qmd
            text: WA1
          - href: wa/wa-member2.qmd
            text: WA2
          - href: wa/wa-member3.qmd
            text: WA3




format:
  html:
    theme: # bootswatch themes--other options https://bootswatch.com/
      light: flatly
      dark: darkly
    search: true
    toc: true
    toc-depth: 3
    link-external-newwindow: true
    css: style/custom.css
    fontsize: 1em
    smooth-scroll: true
    code-overflow: scroll
    code-copy: true
    code-link: true
    code-line-numbers: true
    code-block-bg: true
    code-block-border-left: "#1482FA"
    code-tools: true
    page-layout: full
    code-fold: true
    number-sections: false
    toc-expand: true
    # grid:
    #   sidebar-width: 200px
    #   body-width: 950px
    #   margin-width: 150px

  # pdf:
  #   documentclass: scrreprt
  #   keep-tex: false



execute:
  echo: true
  warning: false
  error: false
  cache: false
#   freeze: auto # remove when using GitHub action to execute code



editor:
  mode: source
  markdown:
    wrap: sentence # Forces each sentence to be on its own line in source markdown, however, it doesn't affect how it is rendered
